<a href="https://colab.research.google.com/github/Ekaterina-Kostina/study/blob/main/%D0%9A%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B0_%D0%95_%D0%94_h_w_%222_types_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(c) В.И. Фирсанова | 2024

# Типы данных в Python

1. **Числовые типы**:
   - `int` integer, целое число `7`
   - `float` число с плавающей точкой (десятичная дробь) `7.1`

2. **Булевы перменные**:
   - `Bool` Boolean, принимает значения `True` или `False`

3. **Наборы, последовательности**:
   - `str` string, строка `"hello"`
   - `list`, список `[1, 7.1, "hello"]`, изменяемая последовательность
    - *вложенный список* состоит из множества списков `[[0, 1, 2], [3, 4]]`
   - `tuple`, кортеж `(1, 7.1, "hello), неизменяемая последовательность
    - в кортежах нельзя удалять, добавлять данные; они занимают меньше памяти
   - `dict`, dictionary, словарь `{"number": 1, "word": "hello"}`, пары ключей и значений (key-query)
    - в этом примере ключами будут `"number"` и `"word"`, а значениями - `1` и `"hello"`
  - `set`, множество, неупорядоченный набор уникальных элементов `{1, 2, 3}`
  - `frozenset`, неизменяемое множество (аналог кортежа по отношению к спискам)

4. **None**:
   - `None` можно использовать для создания пустого элемента, как плейсхолдер в функции, для проверки факта наличия объекта в переменной и т.д.

Задачи

1. Угадай число

In [ ]:
import random
magic_number = random.randint(0, 10)

user_number = int(input())

if user_number == magic_number:
  print('Поздравляю, вы угадали!')
else:
  print('А вот и нет! Это число', magic_number)

3
А вот и нет! Это число 8

Обратите внимание на строку `print('А вот и нет! Это число', magic_number)`

`print` может принимать несколько аргументов через запятую и выводить на экран их все!

Используйте это в следующем задании.

2. Приветствие

In [ ]:
print('Введите ваше имя:')
user_name = input()
print('Привет,', user_name)

Введите ваше имя:
Kate
Привет, Kate

3. Конвертер температур

In [ ]:
print('Введите температуру в градусах Цельсия')
Tc = float(input())
Tf = (9/5*Tc)+32
print('Температура в градусах Цельсия:', Tc)
print('Температура в градусах Фаренгейта:', Tf)

Введите температуру в градусах Цельсия
100
Температура в градусах Цельсия: 100.0
Температура в градусах Фаренгейта: 212.0

Как вывести на экран несколько строк?

- Можно вызвать `print` несколько раз

```
print('Вот первая строка')
print('А это вторая строка')
```
- Можно использовать `\n` - символ новой строки

```
print('Вот первая строка \n А это вторая строка')
```

4. Округление и вывод с помощью новой строки

In [ ]:
# результат расчетов в задаче 3 сохранился в переменных
# воспользуемся этим преимуществом!

# округлите оба значения температур в градусах Цельсия и в градусах Фаргентейта
# вы можете преобразовать результат к виду целого числа с помощью int(n); n - число для преобразования
# либо воспользоваться функцией round(n, k), указав в аргументах функции количество знаков после запятой k
# попробуйте оба варианта!

# теперь выведите на экран оба числа
# сделайте это в одну строчку кода:
# используйте символ новой строки, подумайте, куда его добавить
Tc = int(Tc)
Tf = round(Tf, 0)
print('Температура в градусах Цельсия:', Tc, '\nТемпература в градусах Фаренгейта:', Tf)

Температура в градусах Цельсия: 100
Температура в градусах Фаренгейта: 212.0

В задании 4 нам может помочь свойство конкатенации строк.

`print('Hello' + ' ' +'World')`

Но сложение строки с числом невозможно в питоне. Что делать?

5. Конвертирование типов данных

In [12]:
# преобразуйте округленные значения температур к виду строк, применив str(n),
# где n - то, что вы хотите преобразовать к виду строки

# выведите на экран результат:
# используйте конкатенацию строк вместо запятой в функции print
Tc, Tf = str(Tc), str(Tf)
print(Tc + Tf)

100212.0

Чтобы преобразовать один тип данных в другой, мы вызываем функцию, обозначающую этот тип.

Закрепим новый материал.

6. Калькулятор

In [17]:
# запросите у пользователя 2 целых числа
# выполните операции сложения, вычитания, умножения и возведения каждого из чисел во вторую степень
# выведите результат на экран

number_1 = int(input("Введите первое число: "))
number_2 = int(input("Введите второе число: "))
print(
    'Результат сложения', number_1 + number_2,
'\nРезультат вычитания', number_1 - number_2,
'\nРезультат умножения', number_1 * number_2,
'\nРезультат возведения во вторую степень первого числа', number_1 ** 2,
'\nРезультат возведения во вторую степень второго числа', number_2 ** 2
    )

Введите первое число: 5
Введите второе число: 10
Результат сложения 15
Результат вычитания -5
Результат умножения 50
Результат возведения во вторую степень первого числа 25
Результат возведения во вторую степень второго числа 100

7. Анкета

In [18]:
# вспомним множественное присваивание в python
# a, b, c = 0, 1, 2
# используйте множественное присваивание,
# чтобы одной строчкой кода запросить у пользователя имя, возраст и профессию
# выведите на экран полученную информацию

name, age, profession = input('Ваше имя: '), int(input('Ваш возраст: ')), input('Ваша профессия: ')
print('Имя:', name, '\nВозраст:', age, '\nПрофессия:', profession)

Ваше имя: Катя
Ваш возраст: 23
Ваша профессия: методолог
Имя: Катя
Возраст: 23
Профессия: методолог

8. Поменять местами переменные

In [19]:
# множественное присваивание иногда очень полезно
# запросите у пользователя две любые переменные
# это может быть строка или число, на ваш выбор

# поменяйте их местами одной строчкой кода:
# запишите в первую переменную информацию из второй,
# а во вторую переменную - информацию из первой, используя множественное присваивание

# выведите на экран промежуточные и итоговые результаты

element_1, element_2 = input('Введите информацию в первую переменную: '), input('Введите информацию во вторую переменную: ')
print('В первой переменной хранится', element_1, '\nВо второй переменной хранится', element_2)
print('Меняем местами...')
element_1, element_2 = element_2, element_1
print('В первой переменной хранится', element_1, '\nВо второй переменной хранится', element_2)

Введите информацию в первую переменную: яблоко
Введите информацию во вторую переменную: груша
В первой переменной хранится яблоко
Во второй переменной хранится груша
Меняем местами...
В первой переменной хранится груша
Во второй переменной хранится яблоко

9. Дописать функцию

In [22]:
# чаще мы используем множественное присваивание в фунциональном программировании
# например, эта функция считает сумму и произведение двух чисел
# функция принимает на вход (почти как input!) 2 числа
# эти числа запишутся в переменные a и b
def sum_and_product(a, b):
    # напишите здесь код для расчета суммы чисел a и b
    total_sum = a+b
    # а сюда допишите код для подсчета их произведения
    product = a*b
    # функция возвращает результат подсчета - два новых числа
    return total_sum, product

# настало время множественного присваивания
# мы вызывает функцию sum_and_product и передаем ей в качестве аргументов два числа - 5 и 3
# мы помним, что функция возвращает 2 новых числа,
# поэтому результат работы одной функции мы записываем в две переменные: result_sum и result_product
result_sum, result_product = sum_and_product(5, 3)

# выведите на экран result_sum и result_product
print('Сумма', result_sum, '\nПроизведение', result_product)

Сумма 8
Произведение 15

10. Строка и число

In [24]:
# запросите у пользователя 2 числа, используйте str(input())
# сложите два числа, не меняя тип данных, и выведите на экран результат
# преобразуйте числа к виду нужного типа и снова сложите их, выведите результат

# это задание нам уже знакомо:
# попробуйте решить его питонично, используя как можно меньше строк кода
# какие операции можно объединить?
# в каких случаях нам не нужно создавать дополнительные переменные?
num_1, num_2 = str(input('Введите число: ')), str(input('Введите еще одно число: '))
print('Результат сложения', num_1 + num_2)
num_1, num_2 = int(num_1), int(num_2)
print('Результат сложения', num_1 + num_2)

Введите число: 4
Введите еще одно число: 2
Результат сложения 42
Результат сложения 6